// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6cED2a-4Nx7N4Hmhl18S7OJr6qETybjc',
    appId: '1:384104732694:web:bca4a9ff0acaa19cc33d37',
    messagingSenderId: '384104732694',
    projectId: 'udhar-1cfd7',
    authDomain: 'udhar-1cfd7.firebaseapp.com',
    storageBucket: 'udhar-1cfd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdW3eQF_33lIuNmbhDporVfbYL6EX-q2k',
    appId: '1:384104732694:android:330e0947ddd05cd5c33d37',
    messagingSenderId: '384104732694',
    projectId: 'udhar-1cfd7',
    storageBucket: 'udhar-1cfd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2aT-_YAfZeEISz5HYIYCzgTsfns2P11Y',
    appId: '1:384104732694:ios:26c33b0644ac9c3fc33d37',
    messagingSenderId: '384104732694',
    projectId: 'udhar-1cfd7',
    storageBucket: 'udhar-1cfd7.appspot.com',
    iosBundleId: 'com.example.udhar',
  );
}
